#!/bin/bash

set -e
set -u

if [[ -n "${CI}" ]]; then
    set -x
fi

function usage() {
    echo -n \
"Usage: $(basename "$0")
Test container images built from templates.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
		docker \
            run --rm --entrypoint "ls" \
	            "quay.io/azavea/geoserver:$GEOSERVER_VERSION-tomcat$TOMCAT_VERSION-jre$JRE_VERSION-$VARIANT" \
	            "/usr/local/tomcat/webapps" | grep geoserver
    fi
fi

