
version: '3.7'

services:
  pg-master:
    image: 'kartoza/postgis:11.0-2.5'
    # You can optionally mount to volume, to play with the persistence and
    # observe how the slave will behave after restarts.
    volumes:
      - /mnt/cephfs/wfas/postgres:/var/lib/postgresql
    environment:
      # ALLOW_IP_RANGE option is used to specify additionals allowed domains
      # in pg_hba.
      # This range should allow slaves to connect to master
      ALLOW_IP_RANGE: '0.0.0.0/0'

      # We can specify optional credentials
      POSTGRES_USER: 'docker'
      POSTGRES_PASS: 'docker'
      # Setup master replication variables
      #PG_MAX_WAL_SENDERS: 8
      #PG_WAL_KEEP_SEGMENTS: 100
      POSTGRES_DBNAME: gis,wfas
    # You can expose the port to observe it in your local machine
    ports:
      - "7777:5432"
    healthcheck:
      test: "exit 0"
    deploy:
      restart_policy:
        condition: any
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
  pg-slave:
    image: 'kartoza/postgis:11.0-2.5'
    restart: 'always'
    # You can optionally mount to volume, but we're not able to scale it
    # in that case.
    # The slave will always destroy its database and copy from master at
    # runtime
    volumes:
      - /mnt/postgres:/var/lib/postgresql
      #- ./tests:/tests
      #- dbbackups:/backups
    environment:
      # ALLOW_IP_RANGE option is used to specify additionals allowed domains
      # in pg_hba.
      # Not really needed in slaves for the replication, but optionally can
      # be put when slaves are needed to be a failover server when master
      # is down. The IP Range are generally needed if other services wants to
      # connect to this slave
      ALLOW_IP_RANGE: '0.0.0.0/0'

      # REPLICATE_FROM options accepts domain-name or IP address
      # with this in mind, you can also put docker service name, because it
      # will be resolved as host name.
      REPLICATE_FROM: 'pg-master'

      # REPLICATE_PORT will default to 5432 if not specified.
      # REPLICATE_PORT: '5432'
      # In the case where you need to replicate from outside service,
      # you can put the server address and port here, as long as the target
      # where configured as master, and replicable.
#      REPLICATE_FROM: '192.168.1.8'
#      REPLICATE_PORT: '7777'

      # DESTROY_DATABASE_ON_RESTART will default to True if not specified.
      # If specified other than True, it will prevent slave from destroying
      # database on restart
      DESTROY_DATABASE_ON_RESTART: 'True'

      # PROMOTE_MASTER Default empty.
      # If specified with any value, then it will convert current slave into
      # a writable state. Useful if master is down and the current slave needs
      # to be promoted until manual recovery.
      # PROMOTE_MASTER: 'True'

      # For now we don't support different credentials for replication
      # so we use the same credentials as master's superuser, or anything that
      # have replication role.
      POSTGRES_USER: 'docker'
      POSTGRES_PASS: 'docker'
    depends_on:
       - pg-master
    # You can expose the port to observe it in your local machine
    # For this sample, it was disabled by default to allow scaling test
    ports:
      - "7776:5432"
    deploy:
      restart_policy:
        condition: on-failure
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.labels.name == worker1]
  dbbackups:
    image: kartoza/pg-backup:11.0
    hostname: pg-backups
    volumes:
      - /mnt/backups:/backups
    environment:
      - DUMPPREFIX=demo
      - PGUSER=docker
      - PGPASSWORD=docker
      - PGDATABASE=gis
      - PGPORT=5432
      - PGHOST=pg-slave
    depends_on:
       - pg-slave
    deploy:
      restart_policy:
        condition: on-failure
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.labels.name == worker2]
